# Generated by Django 4.2.1 on 2023-05-09 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsliked',
            name='likedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
