# Generated by Django 4.2.1 on 2023-05-09 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud', '0002_alter_eventsliked_likedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsliked',
            name='likedby',
        ),
        migrations.AddField(
            model_name='eventsmodel',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventsliked',
            name='events',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_details', to='crud.eventsmodel'),
        ),
    ]
